#![doc= " The `error` module defines the error and result types."]

use std::io;
use std::result;

#[doc= " An error that prevents succesful decoding of the FLAC stream."]
#[derive(Debug)]
pub(crate) enum Error {
    #[doc= " Not a decoding error, but a problem with the underlying IO."]
    IoError(io::Error),
    #[doc= " An ill-formed FLAC stream was encountered."]
    FormatError(&'static str),
    #[doc= " A currently unsupported feature of the FLAC format was encountered."]
    #[doc= ""]
    #[doc= " Claxon reads the FLAC format as it was with FLAC 1.3.1. Values in the"]
    #[doc= " specification that are marked as reserved will cause a `FormatError`;"]
    #[doc= " `Unsupported` is used for features that are in the specification, but"]
    #[doc= " which are not implemented by Claxon."]
    Unsupported(&'static str),
}

impl From<io::Error> for Error {
    fn from(err: io::Error) -> Error {
        Error::IoError(err)
    }
}

#[doc= " A type for results generated by Claxon where the error type is hard-wired."]
pub(crate) type Result<T> = result::Result<T, Error>;

#[doc= " Shorthand for producing a format error with reason."]
pub(crate) fn fmt_err<T>(reason: &'static str) -> Result<T> {
    Err(Error::FormatError(reason))
}
