unstable_features = true
edition = "2024"
use_small_heuristics = "Off"

# Use tab characters for indentation, spaces for alignment
#   Default value: false
hard_tabs = true
# Number of spaces per tab
#   Default value: 4
tab_spaces = 13
# Maximum width of each line
#   Default value: 100
max_width = 60
# Break comments to fit on the line
#  Default value: false
wrap_comments = true
# Maximum length of comments. No effect unless wrap_comments = true.
#   Default value: 80
comment_width = 30
# Convert #![doc] and #[doc] attributes to //! and /// doc comments.
#   Default value: false
normalize_doc_attributes = true
# Format code snippet included in doc comments.
#   Default value: false
format_code_in_doc_comments = true
# Max width for code snippets included in doc comments. Only used if format_code_in_doc_comments is true.
#   Default value: 100
doc_comment_code_block_width = 40
# Maximum width of an array literal before falling back to vertical formatting. 
#   Default value: 60
array_width = 0
# Maximum width of the args of a function-like attributes before falling back to vertical formatting.
#   Default value: 70
attr_fn_like_width = 0
# Maximum width of a chain to fit on one line.
#   Default value: 60
chain_width = 0
# Maximum width of the args of a function call before falling back to vertical formatting.
#   Default value: 60
fn_call_width = 0
# Maximum width in the body of a struct variant before falling back to vertical formatting.
#     Default value: 35
struct_variant_width = 0
# Maximum line length for single line if-else expressions.
#   Default value: 50
single_line_if_else_max_width = 0
# Maximum line length for single line let-else statements.
#   Default value: 50
single_line_let_else_max_width = 0
# Brace style for items
#   Default value: "SameLineWhere"
brace_style = "AlwaysNextLine"
# Brace style for control flow constructs
#   Default value: "AlwaysSameLine"
control_brace_style = "AlwaysNextLine"
# Where to put a binary operator when a binary expression goes multiline.
#   Default value: "Front"
binop_separator = "Back"
# Controls whether arm bodies are wrapped in cases where the first line of the body cannot fit on the same line as the => operator.
#   Default value: true
match_arm_blocks = false
# Controls whether to include a leading pipe on match arms
#   Default value: Never
match_arm_leading_pipes = "Always"
# Put a trailing comma after a block based match arm (non-block arms are not affected)
#   Default value: false
match_block_trailing_comma = true
# How to handle trailing commas for lists
#   Default value: "Vertical"
trailing_comma = "Always"
# Controls how imports are structured in use statements. Imports will be merged or split to the configured level of granularity.
#   Default value: Preserve
imports_granularity = "Item"
# Controls the strategy for how consecutive imports are grouped together.
#   Default value: Preserve
group_imports = "One"
# Item layout inside a imports block
#   Default value: "Mixed"
imports_layout = "Vertical"
# Indent style of imports
#   Default Value: "Block"
imports_indent = "Visual"
# Indent on expressions or items.
#   Default value: "Block"
indent_style = "Visual"
# Reorder impl items. type and const are put first, then macros and methods.
#   Default value: false
reorder_impl_items = true
# Minimum number of blank lines which must be put between items. If two items have fewer blank lines between them, additional blank lines are inserted.
#   Default value: 0
blank_lines_lower_bound = 3
# Maximum number of blank lines which can be put between items. If more than this number of consecutive empty lines are found, they are trimmed down to match this integer.
#   Default value: 1
blank_lines_upper_bound = 10
# Put single-expression functions on a single line
#   Default value: false
fn_single_line = true
# Control the layout of parameters in function signatures.
#   Default value: "Tall"
fn_params_layout = "Vertical"
# Forces the where clause to be laid out on a single line.
#   Default value: false
where_single_line = true
# Force multiline closure and match arm bodies to be wrapped in a block
#   Default value: false
force_multiline_blocks = true
# Format the bodies of declarative macro definitions.
#   Default value: true
format_macro_bodies = true
# Format the metavariable matching patterns in macros.
#   Default value: false
format_macro_matchers = true
# Format string literals where necessary
#   Default value: false
format_strings = true
# When structs, slices, arrays, and block/array-like macros are used as the last argument in an expression list, allow them to overflow (like blocks/closures) instead of being indented on a new line.
#   Default value: false
overflow_delimited_expr = true
# Replace strings of _ wildcards by a single .. in tuple patterns
#   Default value: false
condense_wildcard_suffixes = true
# Determines if + or = are wrapped in spaces in the punctuation of types
#   Default value: "Wide"
type_punctuation_density = "Compressed"
# Put spaces around the .., ..=, and ... range operators
#   Default value: false
spaces_around_ranges = true
error_on_line_overflow = false
error_on_unformatted = false
# Put empty-body functions and impls on a single line
#   Default value: true
empty_item_single_line = false
# The maximum length of enum variant having discriminant, that gets vertically aligned with others. Variants without discriminants would be ignored for the purpose of alignment.
#   Default value : 0
enum_discrim_align_threshold = 100
# Convert /* */ comments to // comments where possible
#   Default value: false
normalize_comments = true
# Leave a space before the colon.
#   Default value: false
space_before_colon = true
# Put small struct literals on a single line
#   Default value: true
struct_lit_single_line = false
# Maximum width in the body of a struct literal before falling back to vertical formatting.
#     Default value: 18
struct_lit_width = 0
