#![doc= " Claxon, a FLAC decoding library."]
#![doc= ""]
#![doc= " Examples"]
#![doc= " ========"]
#![doc= ""]
#![doc= " The following example computes the root mean square (RMS) of a FLAC file."]
#![doc= ""]
#![doc= " ```"]
#![doc= " # use claxon;"]
#![doc= " let mut reader = claxon::FlacReader::open(\"testsamples/pop.flac\").unwrap();"]
#![doc= " let mut sqr_sum = 0.0;"]
#![doc= " let mut count = 0;"]
#![doc= " for sample in reader.samples() {"]
#![doc= "     let s = sample.unwrap() as f64;"]
#![doc= "     sqr_sum += s * s;"]
#![doc= "     count += 1;"]
#![doc= " }"]
#![doc= " println!(\"RMS is {}\", (sqr_sum / count as f64).sqrt());"]
#![doc= " ```"]
#![doc= ""]
#![doc= " A simple way to decode a file to wav with Claxon and"]
#![doc= " [Hound](https://github.com/ruuda/hound):"]
#![doc= ""]
#![doc= " ```"]
#![doc= " # extern crate hound;"]
#![doc= " # extern crate claxon;"]
#![doc= " # use std::path::Path;"]
#![doc= " # fn decode_file(fname: &Path) {"]
#![doc= " let mut reader = claxon::FlacReader::open(fname).expect(\"failed to open FLAC stream\");"]
#![doc= ""]
#![doc= " let spec = hound::WavSpec {"]
#![doc= "     channels: reader.streaminfo().channels as u16,"]
#![doc= "     sample_rate: reader.streaminfo().sample_rate,"]
#![doc= "     bits_per_sample: reader.streaminfo().bits_per_sample as u16,"]
#![doc= "     sample_format: hound::SampleFormat::Int,"]
#![doc= " };"]
#![doc= ""]
#![doc= " let fname_wav = fname.with_extension(\"wav\");"]
#![doc= " let opt_wav_writer = hound::WavWriter::create(fname_wav, spec);"]
#![doc= " let mut wav_writer = opt_wav_writer.expect(\"failed to create wav file\");"]
#![doc= ""]
#![doc= " for opt_sample in reader.samples() {"]
#![doc= "     let sample = opt_sample.expect(\"failed to decode FLAC stream\");"]
#![doc= "     wav_writer.write_sample(sample).expect(\"failed to write wav file\");"]
#![doc= " }"]
#![doc= " # }"]
#![doc= " ```"]
#![doc= ""]
#![doc= " Retrieving the artist metadata:"]
#![doc= ""]
#![doc= " ```"]
#![doc= " # use claxon;"]
#![doc= " let reader = claxon::FlacReader::open(\"testsamples/pop.flac\").unwrap();"]
#![doc= " for artist in reader.get_tag(\"ARTIST\") {"]
#![doc= "     println!(\"{}\", artist);"]
#![doc= " }"]
#![doc= " ```"]
#![doc= ""]
#![doc= " For more examples, see the [examples](https://github.com/ruuda/claxon/tree/master/examples)"]
#![doc= " directory in the crate."]
#![warn(missing_docs)]

mod crc;
mod error;
#[cfg(not(KEEP_CARGO_MINIMIZE))]
pub(crate) mod frame;
pub(crate) mod input;
#[cfg(not(KEEP_CARGO_MINIMIZE))]
pub(crate) mod subframe;
