name: Cargo Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Using nightly toolchain because mizan-mut depends on rust-analyzer crates
      # which require nightly features
      - name: Set up Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Validate Rust version
        run: rustc --version
        shell: bash

      - name: Build the Rust workspace
        run: cargo build --workspace
